apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
  namespace: aria-config
data:
  POSTGRES_USER: saltapi
  POSTGRES_PASSWORD: abc123
  POSTGRES_DB: postgres

---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: aria-config
  labels:
    app: postgres
spec:
  os: { name: linux }
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: postgres
    # image: registry.k8s.io/test-webserver:latest
    image: docker.io/library/postgres:15.4
    env:
      - name: POSTGRES_USER
        value: salteapi
      - name: POSTGRES_PASSWORD
        value: abc123
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata
  volumes:
  - name: pgdata
    hostPath:
      # Ensure the file directory is created.
      path: /Users/jordanke/devel/Aria-Config-Docker-Lab/data/postgres
      type: DirectoryOrCreate
